add level to recipes + tests
knowde-academy/team-3-be pull request #1
Opened 2021-08-13 07:22 UTC by morales-cmd

2021-08-13 07:51 UTC, morales-cmd commented
link to trello task:
https://trello.com/c/a2gqkpAT/26-be-add-level-field-to-recipes-return-it-in-response-l

2021-08-13 09:22 UTC, PatrykTyszka requested changes

2021-08-13 09:22 UTC, PatrykTyszka commented on api_contract.txt
> +GET - /api/v1/recipes
Maybe would be better to use markdown here and create a separate file per MODEL

2021-08-13 09:22 UTC, PatrykTyszka commented on app/models/recipe.rb
> +  validates :level, numericality:{only_integer:true, less_than_or_equal_to:5, greater_than_or_equal_to:1, allow_nil:true}
```suggestion
  validates :level, numericality:{ only_integer: true, less_than_or_equal_to: 5, greater_than_or_equal_to: 1, allow_nil: true }
```

2021-08-13 09:22 UTC, PatrykTyszka commented on app/serializers/recipe_serializer.rb
> +     end
WAT? :D

2021-08-13 09:22 UTC, PatrykTyszka commented on app/serializers/recipe_serializer.rb
> +     end
```suggestion
     return UNKNOWN unless object.level
     
     object.level
```

2021-08-13 09:22 UTC, PatrykTyszka commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +      end
Try working with Rspec in this way ->
```suggestion
      let(:call) do
        post :create, params: { recipe: { name: name, content: content, level: level } }
      end
      
      context 'doesn\'t create recipe with level out of range' do
        let(:name) { 'Leczo' }
        let(:content) { 'Very good dish' }
        let(:level) { 8 }
        
        it do
          expect { call }.not_to change(Recipe, :count)
        end
      end
```

2021-08-13 09:22 UTC, PatrykTyszka commented on spec/factories/recipes.rb
> +    level {1}
```suggestion
    level { 1 }
```

2021-08-13 09:22 UTC, PatrykTyszka commented on spec/models/recipe_spec.rb
> +
remove empty line

2021-08-13 09:22 UTC, PatrykTyszka commented on spec/models/recipe_spec.rb
> +        recipe = Recipe.new(recipe_params)
use factory

2021-08-13 09:22 UTC, PatrykTyszka commented on spec/models/recipe_spec.rb
> +        recipe_params['level']=3
```suggestion
        recipe_params['level'] = 3
```

2021-08-13 09:22 UTC, PatrykTyszka commented on spec/models/recipe_spec.rb
> +      end
Try to use let's as I said above.

2021-08-13 09:22 UTC, PatrykTyszka commented on spec/serializers/recipe_serializer_spec.rb
> +    end
```suggestion
  context 'when level is nil' do
    let(:recipe) { build(:recipe, level:nil) }
    
    it { is_expected.to include(level: 'unknown') }
  end
```

2021-08-13 09:22 UTC, PatrykTyszka commented on spec/serializers/recipe_serializer_spec.rb
> +    end
Please try to keep correct indentation everywhere.

2021-08-14 19:52 UTC, PatrykTyszka commented on api_contract.md
> +># GET - /api/v1/recipes
GJ

2021-08-14 19:52 UTC, PatrykTyszka commented on api_contract.txt
> +GET - /api/v1/recipes
remove this file

2021-08-14 19:52 UTC, PatrykTyszka commented on app/serializers/recipe_serializer.rb
> +  def level
```suggestion
  UNKNOWN = 'unknown'
  
  attributes :id, :name, :content, :level
  
  def level
```

2021-08-14 19:52 UTC, PatrykTyszka commented on spec/serializers/recipe_serializer_spec.rb
> +  context 'when level is nil' do
```suggestion
  it { is_expected.to include(level: recipe.level) }
  
  context 'when level is nil' do
```

2021-08-14 19:52 UTC, PatrykTyszka commented on spec/serializers/recipe_serializer_spec.rb
> +    it{ is_expected.to include(level: 'unknown') }
```suggestion
    it { is_expected.to include(level: 'unknown') }
```

2021-08-14 20:12 UTC, morales-cmd commented on api_contract.md
> +># GET - /api/v1/recipes
it's actually Łukasz 's job :P

2021-08-15 19:04 UTC, sebastiansito requested changes

2021-08-15 19:04 UTC, sebastiansito commented on app/models/recipe.rb
> +  validates :level, numericality:{ only_integer: true, less_than_or_equal_to: 5, greater_than_or_equal_to: 1, allow_nil: true }
That lin is probably too long.
Use space after `:`
You can install `rubocop` and it will show you errors and problems like this one right of the bat.

2021-08-15 19:04 UTC, sebastiansito commented on app/serializers/recipe_serializer.rb
> +  end
`Recipe#level` should be always there and we shouldn't need that.

2021-08-15 19:04 UTC, sebastiansito commented on db/migrate/20210811124428_add_levels_to_recipes.rb
> +    add_column :recipes, :level, :integer
Should we add defaults?

2021-08-15 19:04 UTC, sebastiansito commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +      post :create, params: { recipe: { name: name, content: content, level: level } }
`let` is used only to make memoizable variables. This should be called in either `before` block or in the test case itself.

2021-08-15 19:04 UTC, sebastiansito commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +    let(:content) { 'Very good dish' }
```suggestion
    let(:content) { 'Very good meal' }
```
Dish would rather mean the plate itself not a meal.

2021-08-15 19:04 UTC, sebastiansito commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +      it 'creates recipe' do
RSpec will create these descriptions for you so it's better to skip them

2021-08-15 19:04 UTC, sebastiansito commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +    context 'with nil level' do
Should it create recipe without a level?

2021-08-15 19:04 UTC, sebastiansito commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +      it 'doesn\'t create recipe' do
Please just use double quotes, that looks ridiculous 😄

2021-08-15 19:04 UTC, sebastiansito commented on spec/models/recipe_spec.rb
> +    end
You can use https://github.com/thoughtbot/shoulda-matchers gem to automate specs like these

2021-08-15 20:12 UTC, morales-cmd commented on db/migrate/20210811124428_add_levels_to_recipes.rb
> +    add_column :recipes, :level, :integer
Do you mean default level? Ticket says that level may be nil and in that case we return 'unknown' and it already is taken care of in serializer. Or did i misunderstand you?

2021-08-15 20:45 UTC, sebastiansito commented on db/migrate/20210811124428_add_levels_to_recipes.rb
> +    add_column :recipes, :level, :integer
Yup, all good.

2021-08-16 07:56 UTC, morales-cmd commented on spec/models/recipe_spec.rb
> +    end
should i replace them if i already wrote these tests?

2021-08-16 09:57 UTC, sebastiansito commented on spec/models/recipe_spec.rb
> +    end
Let's replace the one in the model

2021-08-16 10:26 UTC, morales-cmd commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +      post :create, params: { recipe: { name: name, content: content, level: level } }
just changed the name of variable as agreed with Patryk

2021-08-17 07:15 UTC, h4b00 approved these changes
Approved.

2021-08-17 07:15 UTC, h4b00 commented on spec/serializers/recipe_serializer_spec.rb
> +
unncessary

2021-08-17 07:15 UTC, h4b00 commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +    end
this is covered by model specs so it's optional to have it.

2021-08-17 07:15 UTC, h4b00 commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +        expect { post_create_request }.not_to change(Recipe, :count)
Same as above.

2021-08-17 07:28 UTC, PatrykTyszka approved these changes

2021-08-17 09:11 UTC, merged