At 29 be add price field l + tests
knowde-academy/team-3-be pull request #2
Opened 2021-08-13 07:47 UTC by Elkorm98

https://trello.com/c/HIWPVKud/29-be-add-price-field-l

2021-08-13 09:09 UTC, PatrykTyszka approved these changes

2021-08-13 09:09 UTC, PatrykTyszka commented on app/serializers/recipe_serializer.rb
> +        return 'unknown' unless object.price
use constant here instead of string.

2021-08-13 09:23 UTC, PatrykTyszka commented on app/serializers/recipe_serializer.rb
> +        return 'unknown' unless object.price
incorect indentation

2021-08-13 10:37 UTC, PatrykTyszka commented on spec/serializers/recipe_serializer_spec.rb
> +
remove

2021-08-13 10:38 UTC, PatrykTyszka commented on spec/serializers/recipe_serializer_spec.rb
> +    let(:recipe) { FactoryBot.build(:recipe) }
FactoryBot - is not necessary

2021-08-13 10:38 UTC, PatrykTyszka approved these changes

2021-08-14 19:49 UTC, PatrykTyszka commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +        end
First of all, please assign JSON.parse() result to the variable to you don't have to call this method twice.
Second - please create two separate expect instead of using and - it will be more readable.

2021-08-14 19:49 UTC, PatrykTyszka commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +        .and JSON.parse(response.body['price']).to eq(recipe.price)
same here

2021-08-14 19:49 UTC, PatrykTyszka commented on spec/serializers/recipe_serializer_spec.rb
> +
remove empty line

2021-08-15 19:22 UTC, sebastiansito requested changes

2021-08-15 19:22 UTC, sebastiansito commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +      it 'updates price' do
RSpec is actually creating descriptions on it's own if you skip them — good to know.

2021-08-15 19:22 UTC, sebastiansito commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +          put :update, params: { id: recipe.id, recipe: { price: new_price } }
Nice 👍

2021-08-15 19:22 UTC, sebastiansito commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +        recipeJSON = JSON.parse(response.body)
Use `let`s

2021-08-15 19:22 UTC, sebastiansito commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +        end
These can be one-liners
```suggestion
        expect { recipeJSON['name'].to eq(new_name) }
```

2021-08-15 19:22 UTC, sebastiansito commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +      recipeJSON = JSON.parse(response.body)
Same here, we should use `let`

2021-08-15 19:22 UTC, sebastiansito commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +        end
These could be one-liners

2021-08-15 19:22 UTC, sebastiansito commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +end
Please fix your code editor to automatically add new lines

2021-08-15 19:22 UTC, sebastiansito commented on spec/factories/recipes.rb
> +    price { rand(1..100) }
It's better not to use random like that, just specify some price

2021-08-15 19:22 UTC, sebastiansito commented on spec/models/recipe_spec.rb
> +    end
Line 7 already tests that

2021-08-15 19:22 UTC, sebastiansito commented on spec/serializers/recipe_serializer_spec.rb
> +  end
https://github.com/thoughtbot/shoulda-matchers should test that already

2021-08-16 07:45 UTC, Elkorm98 commented on spec/serializers/recipe_serializer_spec.rb
> +  end
Patryk said that 'should' should be used on model not in serializer and i want to add some test to serializer too

2021-08-16 09:58 UTC, sebastiansito commented on spec/serializers/recipe_serializer_spec.rb
> +  end
Patryk is right, I though that was a model :)

2021-08-17 07:09 UTC, h4b00 approved these changes
1 small style change.

2021-08-17 07:09 UTC, h4b00 commented on app/serializers/recipe_serializer.rb
> +  UNKNOWN = 'unknown'.freeze
move const to the first line of class.

2021-08-17 07:09 UTC, h4b00 commented on app/serializers/recipe_serializer.rb
> +    return UNKNOWN unless object.price
👍

2021-08-17 07:25 UTC, PatrykTyszka approved these changes

2021-08-17 07:27 UTC, merged