add video_link field + tests
knowde-academy/team-3-be pull request #3
Opened 2021-08-16 11:01 UTC by Elkorm98

https://trello.com/c/lHUW3Mht/27-be-add-videolink-field-to-recipes-return-it-in-response-l

2021-08-16 11:20 UTC, h4b00 approved these changes
Fix just this camelCase.
The rest looks good!

2021-08-16 11:20 UTC, h4b00 commented on app/serializers/recipe_serializer.rb
> +  UNKNOWN = 'unknown'
.freeze

2021-08-16 11:20 UTC, h4b00 commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +    let(:recipeJSON) { JSON.parse(response.body) }
don't use camel syntax use ``_

2021-08-16 11:20 UTC, h4b00 requested changes
missing migration?

2021-08-16 11:24 UTC, sebastiansito requested changes

2021-08-16 11:24 UTC, sebastiansito commented on app/models/recipe.rb
> +  validates :video_link, url: { no_local: true, schemes: ['https'] }, length: { in: 10..100 }, allow_blank: true
Do not use hardcoded numbers or other values like that. Everyone will immediately wonder why 10-100 not for example 20-200. Code should be written in a way that the intent is clear
```suggestion
  URL_MIN_LENGTH = 10
  URL_MAX_LENGTH = 100
  
  validates :video_link, url: { no_local: true, schemes: ['https'] }, length: { in: URL_MIN_LENGTH..URL_MAX_LENGTH }, allow_blank: true
```
When you do that you'll see that URLs cannot be capped at 100 characters. They are 2048 max (https://www.google.com/search?q=url+max+length&oq=url+max+le&aqs=chrome.0.0i512j69i57j0i512l4j0i22i30l4.1280j0j7&sourceid=chrome&ie=UTF-8).
Also why do we check for URL length? Is URL validator not enough?

2021-08-16 11:24 UTC, sebastiansito commented on app/serializers/recipe_serializer.rb
> +  UNKNOWN = 'unknown'
Consts should be put at the top of the file separated by empty newline from the rest of the code

2021-08-16 11:24 UTC, sebastiansito commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +          video_link: 'https://www.youtube.com/watch?v=60KwNYk09BU'
Use `let` so you don't have to type the same URL all over again.
```suggestion
          let(:video_link) { 'https://www.youtube.com/watch?v=60KwNYk09BU' }
          # ...
          video_link: video_link
```

2021-08-16 11:24 UTC, sebastiansito commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +          post :create, params: { recipe: { name: '', content: '', video_link: 'http://www.youtube.com/watch?v=60KwNYk09BU' } }
If you had `let` you could use it here

2021-08-16 11:24 UTC, sebastiansito commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +    let(:recipeJSON) { JSON.parse(response.body) }
Ruby uses snake case not camel case to name variables
```suggestion
    let(:recipe_json) { JSON.parse(response.body) }
```

2021-08-16 11:24 UTC, sebastiansito commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +        expect do
Good 👏

2021-08-16 11:24 UTC, sebastiansito commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +end
Fix your code editor to add new lines automatically

2021-08-16 11:24 UTC, sebastiansito commented on spec/models/recipe_spec.rb
> +    end
`validate_url` gem comes with RSpec matcher: https://github.com/perfectline/validates_url#with-rspec so you don't have to test that manually

2021-08-16 11:24 UTC, sebastiansito commented on spec/serializers/recipe_serializer_spec.rb
> +  context 'when vide_link is present' do
Indentation is messed up here

2021-08-16 11:24 UTC, sebastiansito commented on spec/serializers/recipe_serializer_spec.rb
> +  context 'when vide_link is present' do
Also, typo `vide_link`

2021-08-16 11:43 UTC, Elkorm98 commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +          post :create, params: { recipe: { name: '', content: '', video_link: 'http://www.youtube.com/watch?v=60KwNYk09BU' } }
link used there is unvalidated

2021-08-17 07:05 UTC, h4b00 requested changes

2021-08-17 07:05 UTC, h4b00 commented on app/serializers/recipe_serializer.rb
> +UNKNOWN = 'unknown'.freeze
this const should be inside the class.

2021-08-17 07:05 UTC, h4b00 commented on db/schema.rb
> +    t.decimal "price", precision: 8, scale: 2
why do you have a price here? you should have just `video_link`

2021-08-17 07:05 UTC, h4b00 commented on spec/controllers/api/v1/recipes_controller_spec.rb
> +          video_link: 'https://www.youtube.com/watch?v=60KwNYk09BU'
@Elkorm98 please do as Seb wrote above ☝️

2021-08-17 07:05 UTC, h4b00 commented on Gemfile
> +gem 'validate_url', '~> 1.0.13'
```suggestion

# url validator
gem 'validate_url', '~> 1.0.13'
```

2021-08-18 09:50 UTC, h4b00 approved these changes

2021-08-18 09:50 UTC, h4b00 commented on app/serializers/recipe_serializer.rb
> +  UNKNOWN = 'unknown'.freeze
Consts should be first.

2021-08-18 09:50 UTC, h4b00 commented on db/schema.rb
> -  end
Why do you want to delete it?

2021-08-18 09:50 UTC, h4b00 requested changes
Fix schema.db

2021-08-19 07:29 UTC, morales-cmd commented on db/schema.rb
> -  end
its actually my fault. I accidentaly merged schema looking like this into master, although there is no migration creating user table. I must have forgotten to make rails db:migrate before merging. My bad, im sorry. Can it be fixed?

2021-08-19 07:44 UTC, sebastiansito commented on db/schema.rb
> -  end
You have to run `rails db:migrate` which will re-create the schema and then commit changes

2021-08-19 07:49 UTC, morales-cmd commented on db/schema.rb
> -  end
should i do it from my branch that was merged or can łukasz just do it from this branch?

2021-08-19 07:52 UTC, Elkorm98 commented on db/schema.rb
> -  end
i think i fixed my schema.rb and its looks like there is no conflicts with master

2021-08-20 19:46 UTC, merged