create CRUD for products + tests
knowde-academy/team-3-be pull request #4
Opened 2021-08-17 12:01 UTC by Elkorm98

https://trello.com/c/G8y8ebym/28-be-add-crud-products-m

AC: Users can create a product is moved to task:
https://trello.com/c/TJ8MAYIo/40-product-management-only-by-logged-users

2021-08-17 23:41 UTC, sebastiansito requested changes

2021-08-17 23:41 UTC, sebastiansito commented on app/controllers/api/v1/products_controller.rb
> +      before_action :set_product, except: %i[create index]
Empty new line after

2021-08-17 23:41 UTC, sebastiansito commented on app/controllers/api/v1/products_controller.rb
> +      before_action :set_product, except: %i[create index]
Use `only` instead of `except` here as it's easier to understand which actions are use this before action without reading the whole controller.

2021-08-17 23:41 UTC, sebastiansito commented on app/controllers/api/v1/products_controller.rb
> +        render json: { data: ActiveModel::SerializableResource.new(Product.all, each_serializer: ProductSerializer) }
- What if we have `10_000_000` products?
- It's rather `ActiveModelSerializers::SerializableResource` if anything. It should work out of the box with Rails:
```suggestion
        render json: { data: Product.all, each_serializer: ProductSerializer }
```
https://github.com/rails-api/active_model_serializers/blob/0-10-stable/docs/general/getting_started.md#rails-integration

2021-08-17 23:41 UTC, sebastiansito commented on app/controllers/api/v1/products_controller.rb
> +        render json: ProductSerializer.new(@product).to_h
Same here
```suggestion
        render json: @product
```
https://github.com/rails-api/active_model_serializers/blob/0-10-stable/docs/general/getting_started.md#rails-integration

2021-08-17 23:41 UTC, sebastiansito commented on app/controllers/api/v1/products_controller.rb
> +          render json: { errors: @product.errors.to_s }, status: :unprocessable_entity
`@product.errors.to_s` will serialize errors object (something like `"#<ActiveModel::Errors:0x0000aaaafd33bc58>"`). What you want is probably `@product.errors.full_messages.join(', ')`

2021-08-17 23:41 UTC, sebastiansito commented on app/controllers/api/v1/products_controller.rb
> +          render json: { errors: @product.errors.to_s }, status: :unprocessable_entity
Same here

2021-08-17 23:41 UTC, sebastiansito commented on app/controllers/api/v1/products_controller.rb
> +        if @product.destroy
Even if there's nothing to destroy `@product.destroy` will return the object itself so it will always work. You don't have to check the condition and you should handle the exception instead.

2021-08-17 23:41 UTC, sebastiansito commented on app/controllers/api/v1/products_controller.rb
> +          render json: { errors: @product.errors.to_s }, status: :unprocessable_entity
Fix errors

2021-08-17 23:41 UTC, sebastiansito commented on db/schema.rb
> +ActiveRecord::Schema.define(version: 2021_08_17_112045) do
Looks like schema is all messed up. If you're adding products I'd expect just the section for products added

2021-08-17 23:41 UTC, sebastiansito commented on spec/controllers/api/v1/products_controller_spec.rb
> +      expect(JSON.parse(response.body)['data'].size).to eq(5)
It only tests the size of the response. Maybe good enough but maybe we could write a better test (e.g. expecting what actually is in the response as opposed to checking if it's 5 things)

2021-08-18 18:34 UTC, sebastiansito approved these changes
Just few more comments, other than that it looks good

2021-08-18 18:34 UTC, sebastiansito commented on app/controllers/api/v1/products_controller.rb
> +        render json: { Message: 'Something went wrong!' }, status: :unprocessable_entity
JSON keys should be lowercase
```suggestion
        render json: { message: 'Something went wrong!' }, status: :unprocessable_entity
```

2021-08-18 18:34 UTC, sebastiansito commented on db/migrate/20210817112045_create_products.rb
> +      t.integer :quantity
Should we put some validations at database level?

2021-08-19 07:10 UTC, Elkorm98 commented on db/migrate/20210817112045_create_products.rb
> +      t.integer :quantity
we need only positive integer but this validation is added in model

2021-08-19 08:15 UTC, sebastiansito commented on db/migrate/20210817112045_create_products.rb
> +      t.integer :quantity
You should still add `default: 0` or sth to avoid `nil` values at db level probably

2021-08-19 08:22 UTC, PatrykTyszka commented on app/controllers/api/v1/products_controller.rb
> +          render json: { errors: @product.errors.full_messages.join(', ') }, status: :unprocessable_entity
did you ask FE if this form of error is OK? I noticed that other send errors.message

2021-08-19 08:22 UTC, PatrykTyszka commented on app/controllers/api/v1/products_controller.rb
> +        render json: { message: 'Record not found!' }, status: :unprocessable_entity
why not error? besides it would be better to send 404 instead of 422 in this case.

2021-08-19 08:22 UTC, PatrykTyszka commented on config/routes.rb
> +      resources :products
please add only here coz we don't need 'edit' and 'new' paths

2021-08-19 08:22 UTC, PatrykTyszka commented on db/migrate/20210817112045_create_products.rb
> +      t.integer :quantity
agree with Seb, should be default

2021-08-19 08:28 UTC, Elkorm98 commented on app/controllers/api/v1/products_controller.rb
> +          render json: { errors: @product.errors.full_messages.join(', ') }, status: :unprocessable_entity
FE is ok with that

2021-08-19 09:26 UTC, merged